trigger:
  branches:
    include:
    - main
  paths:
    include:
    - terraform
    - yaml-templates
pr:
  branches:
    include:
    - main
  paths:
    include:
    - terraform
    - yaml-templates

variables:
- group: 'secrets'
- name: spokeName
  value: xwc
- name: deployFlag # We don't want the Prod stage running twice during a PR
  ${{ if eq(variables['Build.Reason'],'PullRequest') }}:
    value: false
  ${{ if ne(variables['Build.Reason'],'PullRequest') }}:
    value: true


stages:
- template: templates/template-terraform-deploy-stage.yml
  parameters:
    backendAzureRmResourceGroupName: "rg-terraform-statefiles-001"
    backendAzureRmStorageAccountName: "samojtfstate001"
    backendAzureRmContainerName: "tfstate"
    backendAzureRmKey: "xwcapp.terraform.tfstate"
    backendServiceArm:
    deployFlag: true
    environmentName: dev
    githubPat: $(GITHUB_PAT)
    stageName: "dev"
    stageDisplayName: dev
    spokeName: ${{ variables.spokeName }}
    subscription_id:
    tenant_id: "0bb413d7-160d-4839-868a-f3d46537f6af"
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/dev'
    yamlenv: "dev_noapproval"

- template: templates/template-terraform-deploy-stage.yml
  parameters:
    backendAzureRmResourceGroupName: "rg-prod-tfstate-001"
    backendAzureRmStorageAccountName: "samojtfstate003"
    backendAzureRmContainerName: "tfstate"
    backendAzureRmKey: "xwcapp.terraform.tfstate"
    backendServiceArm:
    deployFlag: $(deployFlag)
    environmentName: prod
    githubPat: $(GITHUB_PAT)
    runApply: false
    stageName: prodplan
    stageDisplayName: Prod Plan
    spokeName: ${{ variables.spokeName }}
    subscription_id: dc2ea4ec-a86d-435a-9940-70fe36030bff
    tenant_id: c6874728-71e6-41fe-a9e1-2e8c36776ad8
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/prod'
    yamlenv: prod_noapproval

- template: templates/template-terraform-deploy-stage.yml
  parameters:
    backendAzureRmResourceGroupName: "rg-prod-tfstate-001"
    backendAzureRmStorageAccountName: "samojtfstate003"
    backendAzureRmContainerName: "tfstate"
    backendAzureRmKey: "xwcapp.terraform.tfstate"
    backendServiceArm:
    deployFlag: true
    environmentName: prod
    githubPat: $(GITHUB_PAT)
    stageName: prod
    stageDisplayName: Prod Apply
    spokeName: ${{ variables.spokeName }}
    subscription_id: dc2ea4ec-a86d-435a-9940-70fe36030bff
    tenant_id: c6874728-71e6-41fe-a9e1-2e8c36776ad8
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/prod'
    yamlenv: prod_approval
